/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_poo;

import entities.Article;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author dell
 */
public class JFrameArticle extends javax.swing.JFrame {

    /**
     * Creates new form JFrameArticle
     */
    public JFrameArticle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelLibelle = new javax.swing.JLabel();
        jLabelPrix = new javax.swing.JLabel();
        jLabelQteEnStock = new javax.swing.JLabel();
        jLabelQteSeuil = new javax.swing.JLabel();
        jLabelDateCreation = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldLibelle = new javax.swing.JTextField();
        jTextFieldPrix = new javax.swing.JTextField();
        jTextFieldQteEnStock = new javax.swing.JTextField();
        jTextFieldDateCreation = new javax.swing.JTextField();
        jTextFieldQteSeuil = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelidCat = new javax.swing.JLabel();
        jTextFieldIdCat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(147, 164, 114));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Article");

        jLabelId.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(0, 0, 0));
        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("Id");

        jLabelLibelle.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelLibelle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLibelle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLibelle.setText("Libellé");

        jLabelPrix.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelPrix.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrix.setText("Prix");

        jLabelQteEnStock.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelQteEnStock.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQteEnStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQteEnStock.setText("Quantité En Stock");

        jLabelQteSeuil.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelQteSeuil.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQteSeuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQteSeuil.setText("Quantité Seuille");

        jLabelDateCreation.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelDateCreation.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDateCreation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDateCreation.setText("Date de Création");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jTextFieldLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLibelleActionPerformed(evt);
            }
        });

        jTextFieldQteEnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQteEnStockActionPerformed(evt);
            }
        });

        jTextFieldDateCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateCreationActionPerformed(evt);
            }
        });

        jTextFieldQteSeuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQteSeuilActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jLabelidCat.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabelidCat.setForeground(new java.awt.Color(0, 0, 0));
        jLabelidCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelidCat.setText("Id de la Catégorie");

        jTextFieldIdCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonModifier)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelQteEnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelQteSeuil)
                                .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDateCreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelidCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldId)
                                    .addComponent(jTextFieldLibelle)
                                    .addComponent(jTextFieldPrix)
                                    .addComponent(jTextFieldQteEnStock)
                                    .addComponent(jTextFieldDateCreation)
                                    .addComponent(jTextFieldQteSeuil)
                                    .addComponent(jTextFieldIdCat, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButtonEnregistrer)
                                .addGap(87, 87, 87)
                                .addComponent(jButtonAnnuler)))))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelQteSeuil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelidCat))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLibelle)
                            .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrix)
                            .addComponent(jTextFieldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQteEnStock)
                            .addComponent(jTextFieldQteEnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateCreation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldQteSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonEnregistrer)
                    .addComponent(jButtonAnnuler))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLibelleActionPerformed

    private void jTextFieldQteEnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQteEnStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQteEnStockActionPerformed

    private void jTextFieldDateCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateCreationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldDateCreationActionPerformed

    private void jTextFieldQteSeuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQteSeuilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQteSeuilActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
        int verifie = 0;
        if(!jTextFieldLibelle.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldPrix.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldQteEnStock.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldDateCreation.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldDateCreation.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldQteEnStock.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldQteSeuil.getText().isEmpty()){
            verifie += 1;
        }
        if(!jTextFieldIdCat.getText().isEmpty()){
            verifie += 1;
        }
        if(verifie != 8){
        JOptionPane.showMessageDialog(rootPane, 
                                      "Certains champs sont vides. Veuillez tous les renseigner.", 
                                      "Erreur", 
                                      JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Article enrégistré", "information", JOptionPane.INFORMATION_MESSAGE);
            Article article = new Article();
            //article.setId_Art(Integer.parseInt(jTextFieldId.getText()));
            //article.setId_Cat(Integer.parseInt(jTextFieldIdCat.getText()));
            article.setLibelle(jTextFieldLibelle.getText());
            //article.setPrix();
            article.setQuantiteEnStock(0);
            //article.setDateCreation(jTextFieldDateCreation.getText());
            article.setQuantiteSeuil(Integer.parseInt(jTextFieldQteSeuil.getText()));
     
        }
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jTextFieldIdCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdCatActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDateCreation;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLibelle;
    private javax.swing.JLabel jLabelPrix;
    private javax.swing.JLabel jLabelQteEnStock;
    private javax.swing.JLabel jLabelQteSeuil;
    private javax.swing.JLabel jLabelidCat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDateCreation;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdCat;
    private javax.swing.JTextField jTextFieldLibelle;
    private javax.swing.JTextField jTextFieldPrix;
    private javax.swing.JTextField jTextFieldQteEnStock;
    private javax.swing.JTextField jTextFieldQteSeuil;
    // End of variables declaration//GEN-END:variables
}
